### ISSUE TITLE
Add dbForge Studio for MySQL to GUI section

### ISSUE THREAD

**Issue by JordanS22** [shlomi-noach/awesome-mysql#100] opened 2021-10-19 10:45 UTC
[dbForge Studio for MySQL](https://www.devart.com/dbforge/mysql/studio/) - a universal GUI tool for MySQL and MariaDB database development, management, and administration. It is a full-fledged IDE that helps create and execute queries, develop and debug stored routines, automate database object management, compare and synchronize databases, analyze table data, and much more. Its rich functionality is delivered under an intuitive interface.

**Comment by shlomi-noach** [comment] 2021-10-19 10:53
Duplicate of #70 ; nothing has changed in dbForge since then.

**Closed by shlomi-noach** 2021-10-19 10:53 UTC

**Comment by shlomi-noach** [comment] 2021-10-19 10:58
Thank you for the suggestion, please see discussion in #70
